version: "3.8"
services: 
  gameapptestauto:
    image: litattj/atticusgametest123:latest
    build: .
    container_name: gameapptestautocontainer
    ports:
      - "8081:3000"
    environment:
      - PORT=3000
    volumes:
      - ./:/app
    command: ["node", "app.js"]